### ISSUE TITLE
compile and download 

### ISSUE THREAD

**Issue by olemde** [ariquezada/FFT-spectrum-analyzer#1]
Hello Arien
i don't know if you get informed about hackaday messages. Thats why i try to contact you here:

I have problems in compiling and downloading the arduino code to the device, because i only know how to handle the arduino IDE. But the IDE responses a lot of error messages while compiling. Could you please give me a hint if it possible to compile with the  IDE, or ho to use gcc and avrdude. Both i never used before, so i am in front of very high obstacles....

Thank you very much

Ole

**Comment by ariquezada** [comment]
Hi Ole, It is possible to compile using the Arduino IDE, but you have to use its structure (setup and loop). If you use the IDE, you can use the Serial class to manage the serial port. I wrote the program for Arduino IDE and it´s included with the project files. To configure the timer and ADC it writes directly in the configuration registers. Regards, Ariel.
